[build]
  command = "ng build --configuration=production && npm run json-server && npm install --save-dev npm-run-all"
  publish = "dist/reconectando"

[dev]
  command = "ng serve --open"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/:splat"
  status = 200
